version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: base64:XFEHGQSGYkAcbHHQsmcE43qMgXnA2SJIpWG265meI/k=
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  #   nginx:
  #     image: nginx:alpine
  #     ports:
  #       - '8000:80'
  #     volumes:
  #       - .:/var/www
  #       - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
  #     depends_on:
  #       - app

  redis:
    image: redis:7
    ports:
      - '6380:6379'
    restart: unless-stopped
    volumes:
      - redisdata:/data

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - '5460:5432'
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
#   prometheus:
#     image: prom/prometheus
#     ports:
#       - '9090:9090'
#     volumes:
#       - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml

#   grafana:
#     image: grafana/grafana
#     ports:
#       - '3000:3000'
#     depends_on:
#       - prometheus
#   node-exporter:
#     image: prom/node-exporter
#     container_name: node-exporter
#     ports:
#       - '9100:9100'
#     restart: unless-stopped

volumes:
  redisdata:
  pgdata:
